# Players and aliases.
Alex = A = ALEX = 'Alex'
Andy = ANDY = 'Andy'
Brendan = B = BR = 'Brendan'
Craig = K = CW = CRAIG = KRAG = 'Craig'
Dylan = DYL = DY = 'Dylan'
ED = 'Ed'
Elliot = E = 'Elliot'
Greg = G = GH = GR = GRE = 'Greg'
Jack = JACK = 'Jack'
Jamie = JA = JAMIE = JH = H = JAM = 'Jamie'
JC = 'Justin'
JK = 'Jordan'
Jingbo = J = JING = 'Jingbo'
Maya = M2 = MA = MAYA = 'Maya'
Michael = M = MC = 'Michael C'
MichaelLee = ML = MLE = L = 'Michael L'
Milos = D = MD = MI = MIL = 'Milos'
Nick = N = NICK = NICHOLAS = 'Nick'
Omid = O = OM = 'Omid'
Simon = 'Simon H'
SimonL = SL = SLG = SIML = 'Simon L'
Will = W = WILL = 'Will D'

# Games.
doubles = [
    [Elliot, JC, 7, Brendan, Maya, 10],
    [Elliot, JC, 10, Brendan, Maya, 8],

    [Jamie, Milos, 7, Omid, Jingbo, 10],
    [Elliot, Jingbo, 6, Jamie, Milos, 10],
    [Nick, Brendan, 7, Jamie, Milos, 10],
    [Jingbo, JC, 3, Jamie, Brendan, 10],
    [JC, Michael, 2, Brendan, Jamie, 10],
    [Brendan, Jingbo, 10, Michael, JC, 8],
    [Brendan, Jingbo, 10, Michael, Elliot, 8],
    [Jingbo, Brendan, 10, Michael, Elliot, 6],
    [Jingbo, Brendan, 10, JC, Elliot, 8],
    [Jamie, Milos, 7, Omid, Jingbo, 10],
    [Elliot, Jingbo, 6, Jamie, Milos, 10],
    [Nick, Brendan, 7, Jamie, Milos, 10],
    [Jingbo, JC, 3, Jamie, Brendan, 10],
    [JC, Michael, 2, Brendan, Jamie, 10],
    [Brendan, Jingbo, 10, Michael, JC, 8],
    [Brendan, Jingbo, 10, Michael, Elliot, 8],
    [Jingbo, Brendan, 10, Michael, Elliot, 6],
    [Jingbo, Brendan, 10, JC, Elliot, 8],
    [Elliot, Brendan, 10, Jamie, Michael, 10],
    [Elliot, Michael, 2, Jamie, Jingbo, 10],
    [Michael, Jamie, 6, Brendan, Jingbo, 10],
    [Milos, Michael, 9, JC, M2, 10],
    [Jingbo, Brendan, 10, JC, M2, 3],

    [Brendan, Jingbo, 10, Elliot, Milos, 1],
    [Brendan, Jingbo, 10, Elliot, Milos, 3],
    [Brendan, Jingbo, 10, Elliot, Milos, 3],
    [Jingbo, Michael, 10, Elliot, Brendan, 4],
    [Nick, Jamie, 7, Jingbo, Michael, 10],
    [MichaelLee, Brendan, 10, JC, Michael, 9],
    [Elliot, Jingbo, 10, Craig, Simon, 3],
    [Jamie, Milos, 10, JC, Michael, 7],
    [Elliot, Milos, 10, Brendan, MichaelLee, 7],
    [Jingbo, Milos, 10, Jamie, Brendan, 7],
    [Jamie, Michael, 10, Jingbo, Brendan, 7],
    [SimonL, Greg, 6, Jamie, JC, 10],
    [Michael, Greg, 10, Jamie, JC, 6],
    [Michael, Jingbo, 3, Jamie, JC, 7],

    [Elliot, Brendan, 9, Jingbo, Michael, 10],
    [Jingbo, Michael, 8, Jamie, Brendan, 10],
    [MD, Michael, 10, JC, Omid, 9],
    [Elliot, Jamie, 10, Milos, Brendan, 5],
    [Elliot, Jamie, 8, Milos, Brendan, 10],
    [Michael, Jingbo, 9, Milos, Brendan, 10],
    [Michael, JC, 7, Elliot, Milos, 10],
    [Michael, JC, 10, Elliot, Milos, 8],
    [Elliot, Michael, 6, Jingbo, MA, 10],
    [Elliot, Michael, 10, Milos, Craig, 5],
    [Elliot, Brendan, 7, Milos, Jingbo, 10],
    [Elliot, JC, 6, Jingbo, Michael, 10],
    [Elliot, JC, 5, Jingbo, Michael, 10],
    [Jingbo, Michael, 10, Jamie, Brendan, 4],
    [Jamie, Brendan, 10, Jingbo, Michael, 3],
    [Michael, Jingbo, 10, Brendan, Elliot, 8],

    [Elliot, Jamie, 10, Nick, Greg, 4],
    [Elliot, Jamie, 10, Nick, Greg, 4],
    [Elliot, Jamie, 10, Brendan, Michael, 3],
    [Michael, Brendan, 1, Jamie, Craig, 10],
    [Craig, Elliot, 3, Brendan, Michael, 10],
    [Elliot, Nick, 7, Brendan, Michael, 10],
    [Elliot, Nick, 5, Brendan, Michael, 10],
    [Nick, Greg, 10, JC, Jamie, 8],
    [Nick, Greg, 6, JC, Jamie, 10],
    [Brendan, Elliot, 9, MI, ML, 10],
    [Brendan, Elliot, 10, MI, ML, 5],
    [Brendan, Elliot, 10, MI, ML, 8],
    [Jamie, Elliot, 10, Greg, Nick, 5],
    [Elliot, Jingbo, 10, Jamie, Omid, 7],
    [Elliot, Brendan, 10, Jamie, Milos, 9],
    [Jingbo, Nick, 6, Brendan, Elliot, 10],
    [Brendan, SL, 9, Michael, JC, 10],
    [Brendan, SL, 10, Michael, JC, 9],
    [Brendan, SL, 10, Michael, JC, 9],
    [Jamie, Maya, 10, Elliot, Jingbo, 9],
    [Elliot, Michael, 10, Maya, Jamie, 6],

    [Elliot, Brendan, 10, Maya, Jingbo, 7],
    [Elliot, Jingbo, 10, Alex, Jamie, 3],
    [Michael, Milos, 5, Elliot, Jingbo, 10],
    [Michael, Milos, 10, Elliot, Jingbo, 9],
    [Jingbo, Michael, 10, Elliot, Maya, 5],
    [Elliot, Greg, 4, Jamie, Michael, 10],
    [Jingbo, Maya, 4, Elliot, Michael, 10],
    [Elliot, Michael, 10, Maya, Jingbo, 9],
    [Brendan, Jamie, 10, Elliot, Jingbo, 5],
    [Brendan, Jamie, 10, Elliot, Jingbo, 8],
    [MC, SLG, 10, JC, GH, 9],
    [MC, SLG, 10, Jingbo, GH, 9],
    [MC, SLG, 10, MLE, Milos, 7],
    [MC, Jingbo, 10, MLE, Milos, 8],
    [Elliot, JC, 7, Jamie, Michael, 10],
    [Brendan, Michael, 10, JC, Alex, 5],
    [Elliot, Will, 3, Brendan, Michael, 10],
    [Elliot, ML, 10, Michael, Milos, 5],
    [Elliot, ML, 4, Michael, Milos, 10],
    [Will, Elliot, 7, Michael, Craig, 10],

    [E, M, 10, JA, B, 5],
    [G, B, 10, E, M, 8],
    [E, JC, 8, B, J, 10],
    [JH, Omid, 10, Milos, Craig, 1],
    [JH, Omid, 10, Milos, Craig, 4],
    [JH, Omid, 10, Milos, SLG, 4],
    [JH, Omid, 10, Milos, SLG, 6],
    [JH, JC, 10, B, Nick, 1],
    [JH, JC, 10, B, Nick, 3],
    [E, JA, 10, J, G, 5],
    [E, JA, 4, J, G, 10],
    [JA, Jack, 10, E, B, 1],
    [JH, Jack, 10, E, B, 5],
    [MI, JA, 10, B, N, 1],
    [JC, MC, 9, K, MD, 10],
    [JC, MC, 7, K, ML, 10],
    [JC, MC, 10, MD, ML, 6],
    [JC, MC, 10, O, MD, 7],
    [JC, MC, 10, O, MD, 8],
    [D, O, 10, M, JC, 8],
    [MA, E, 2, B, O, 10],

    [E, JH, 10, N, G, 4],
    [E, JH, 10, N, G, 4],
    [E, JH, 10, B, M, 3],
    [MC, BR, 1, JH, K, 10],
    [K, E, 3, B, M, 10],
    [E, N, 7, B, M, 10],
    [E, N, 5, B, M, 10],
    [N, G, 10, JC, JAMIE, 8],
    [N, G, 6, JC, JAMIE, 10],
    [B, E, 9, MI, ML, 10],
    [B, E, 10, MI, ML, 5],
    [B, E, 10, MI, ML, 8],
    [JH, E, 10, GR, NICK, 5],
    [MAYA, E, 9, B, O, 10],
    [E, J, 10, JA, O, 7],
    [E, B, 10, JA, MI, 9],
    [J, N, 6, B, E, 10],
    [B, SL, 9, MC, JC, 10],
    [B, SL, 10, MC, JC, 9],
    [B, SL, 10, MC, JC, 7],
    [JA, MA, 10, E, J, 9],
    [E, M, 10, MA, JA, 6],

    [G, M, 8, JC, H, 10],
    [G, M, 10, JC, H, 9],
    [E, L, 10, B, D, 9],
    [E, B, 10, E, JACK, 6],
    [D, J, 10, E, B, 2],
    [H, JC, 10, D, J, 9],
    [G, M, 10, D, JC, 3],
    [G, M, 10, H, JC, 2],
    [G, A, 10, B, JC, 4],
    [G, A, 10, B, JC, 4],
    [E, MAYA, 10, B, O, 3],
    [E, MAYA, 10, B, O, 4],
    [E, MAYA, 10, B, JACK, 8],
    [E, MAYA, 9, B, JACK, 10],
    [E, MAYA, 7, B, JACK, 10],
    [E, MAYA, 4, B, JACK, 10],
    [E, MAYA, 5, B, JACK, 10],
    [MC, MD, 10, JC, CW, 7],
    [MC, MD, 10, JC, CW, 3],
    [MC, MD, 4, MLE, H, 10],

    [E, JA, 6, J, B, 10],
    [E, JA, 10, J, B, 8],
    [E, JA, 10, K, W, 2],
    [E, JA, 10, MI, B, 5],
    [B, MD, 10, G, A, 8],
    [WILL, H, 10, CRAIG, NICHOLAS, 4],
    [E, G, 7, J, MI, 10],
    [G, D, 10, B, L, 4],
    [G, D, 10, B, L, 1],
    [B, M, 10, ML, MIL, 8],

    [JC, MI, 10, B, JACK, 9],
    [MI, ML, 10, B, JACK, 5],
    [MI, ML, 10, B, JACK, 4],
    [E, MI, 3, J, MLE, 10],
    [G, MI, 10, JC, SLG, 1],
    [G, MI, 10, JC, SLG, 1],
    [B, N, 10, E, J, 3],
    [JAMIE, DYL, 10, B, MD, 9],
    [E, JC, 10, B, DY, 7],
    [E, JC, 3, B, JAMIE, 10],
    [E, JC, 2, B, JAMIE, 10],
    [E, B, 0, JC, JAMIE, 10],
    [G, ANDY, 10, WILL, JK, 10],
    [E, J, 1, B, N, 10],
    [E, J, 9, B, N, 10],
    [E, B, 7, MI, J, 10],
    [JAM, E, 10, B, G, 9],
    [JAM, MD, 10, JC, SLG, 7],
    [E, JAM, 4, J, B, 10],
    [E, JAM, 2, J, B, 10],
    [B, K, 4, JC, DY, 10],
    [MD, JING, 10, B, NICK, 4],
    [MD, JING, 10, B, NICK, 2],
    [B, ED, 10, E, KRAG, 5],
    [SIML, MD, 10, ML, OM, 4],
    [B, E, 10, A, MI, 5],
    [B, E, 6, J, MI, 10],
    [B, E, 8, J, MI, 10],
    [MA, E, 2, JAM, N, 10],
    [E, JACK, 10, N, A, 5],
    [G, ALEX, 10, SLG, NICK, 1],
    [MLE, JACK, 10, ALEX, SIML, 7],
    [JAM, SLG, 10, GRE, NICK, 9],
    [JAM, GRE, 10, J, E, 7],
    [E, J, 10, MAYA, JAM, 6]
]
